### ISSUE TITLE
Changes in view-model are not propagated

### ISSUE THREAD

**Issue by warpech** [Starcounter/starcounter-debug-aid#38]
Changes made in JSON editor of the view-model are not propagated to PuppetJS. This used to work some time ago.

**Comment by tomalec** [comment]
That's probably some long time ago we switched from my fork of JSONEditor to original one - which worked with `dom-bind-notifier` (`Object.observe` magic) but does not without it.

It comes back to `juicy-jsoneditor` not working with Polymer's buggy two-way data-binding, as Polymer does `newVal !== oldVal` checks everywhere.

**Comment by tomalec** [comment]
@warpech Do you think we have somebody in the team who can work on it?

**Comment by warpech** [comment]
@alshakero. This should be tracked in Palindrom TF.
