### ISSUE TITLE
Load on demand

### ISSUE THREAD

**Issue by warpech** [Starcounter/starcounter-debug-aid#42]
Starcounter-debug-aid's size is about 300 KB, and it is by far the biggest resource that affects the page load. Removing it decreases the page load from 1s to 500 ms.

We should change the custom element to only register the keyboard hot key. After pressing the hot key, everything else should be loaded on demand.

@tomalec do you have some idea how to do that? Is that Polymer lazy loading?

**Comment by tomalec** [comment]
I'd lazy load most of the elements. I thing Polymer's lazy-import should do
the job.

29 lis 2016 09:42 "Marcin Warpechowski" <notifications@github.com>
napisał(a):

**Comment by warpech** [comment]
@diliger could you possibly take this?

**Comment by warpech** [comment]
Assigning to @diliger as discussed on Slack

**Comment by diliger** [comment]
as agreed in slack will be done till Monday

**Comment by warpech** [comment]
To work on this issue it is enough to do the work in this repo, outside of any Starcounter project.

Just make a local clone of this repo following the instructions at: https://github.com/Starcounter/starcounter-debug-aid/blob/master/CONTRIBUTING.md

When this issue is done correctly, the whole component, including the dependencies which are currently at the top of https://github.com/Starcounter/starcounter-debug-aid/blob/c6201985b0bb2ee564fb11af18f250bdfa09a95c/src/starcounter-debug-aid.html#L11-L14 will only be loaded only after the hotkey is pressed (<kbd>CTRL</kbd>+<kbd>&#96;</kbd>, or another key if you have non-international keyboard - see README).

Perhaps a new element `starcounter-debug-aid-ui` needs to be created and current `starcounter-debug-aid` needs to be limited to keyboard event handlers and Polymer lazy load.

**Comment by warpech** [comment]
The files that I expect to be removed from initial page load are marked with a red arrow. This is 649 KB in total.

![screen shot 2016-12-09 at 11 51 38](https://cloud.githubusercontent.com/assets/566463/21046706/38b0b082-be06-11e6-8fe8-64a3938247e4.png)

**Comment by warpech** [comment]
The technique in which we do this should be applicable to https://github.com/Starcounter/starcounter-layout-html-editor as well.

**Comment by warpech** [comment]
This is being implemented in #43

**Comment by warpech** [comment]
Done
