### ISSUE TITLE
Improve lazy loading

### ISSUE THREAD

**Issue by warpech** [Starcounter/starcounter-debug-aid#44]
@diliger, could you please check if suggestions made by @tomalec in https://github.com/Starcounter/starcounter-debug-aid/pull/43#discussion_r94347727 make the implementation less hacky? 

Especially try `this.importHref`. 

I don't care about `lazy-imports.html` here too much, because I feel that it is a hack itself.

**Comment by diliger** [comment]
Unfortunately `this.importHref` doesn't resolve URL as expected as well...

Should I turn to `lazy-imports`?

**Comment by warpech** [comment]
No, then let's leave it as it is. Thanks investigating this.

**Comment by tomalec** [comment]
@diliger have you checked `this.resolveUrl` as well? I think it would be safer to use this. As now Polymer is more in charge of HTML Imports than w3c spec or browser.

**Comment by diliger** [comment]
Yes! `resolveUrl` does the magic
PR #45
