### ISSUE TITLE
Make sure starcounter-debug-aid works with Palindrom

### ISSUE THREAD

**Issue by warpech** [Starcounter/starcounter-debug-aid#47]
Since Palindrom 3.0.0 removes event triggering from Palindrom constructor, `starcounter-debug-aid` needs to switch to using callbacks to catch incoming and outgoing patches from Palindrom.

@alshakero pls make sure `starcounter-debug-aid` continues working with Palindrom

**Comment by alshakero** [comment]
Up

**Comment by alshakero** [comment]
This is done in https://github.com/Starcounter/starcounter-debug-aid/commit/896ccef1cc9fdba2cbad865fc532d424676a03d9
