### ISSUE TITLE
Remember user open choice (Overlay | Popup) and don't ask for the second time

### ISSUE THREAD

**Issue by miyconst** [Starcounter/starcounter-debug-aid#53]
It would be very nice if the extension would remember it's last state (overlay or popup) and restore it's state on the icon click without asking how to open it again.

**Comment by alshakero** [comment]
Done in Chrome in https://github.com/Starcounter/starcounter-debug-aid/commit/16e14557bc67051e82b409489cac1e3ad922107b

Soon I'll do Firefox. Sadly storage API isn't the same for the two.
