### ISSUE TITLE
Keep the popup window open on page reload

### ISSUE THREAD

**Issue by miyconst** [Starcounter/starcounter-debug-aid#54]
Is it possible to keep the popup window open during the page reload? If so, then it should definitely stay open until user closes it.

**Comment by alshakero** [comment]
The natural case is that it stays open. I had to add some logic to actually close it. Because when you refresh it detaches from the window and becomes meaningless :( 

I can leave it open, but that would be useless.

**Comment by miyconst** [comment]
>I can leave it open, but that would be useless.

Nah, it should reconnect to the new window ;), otherwise it's not possible to see the patches sent/received before the window was open.

**Comment by alshakero** [comment]
Wow, turns out each pop-up has a string refresh that you can reference! I'll check.

**Comment by alshakero** [comment]
Done in https://github.com/Starcounter/starcounter-debug-aid/commit/6d067038e1e774dcefeaa590b12dee84a64d1283.
