### ISSUE TITLE
Double click on a patch content shows JSON tree with empty objects

### ISSUE THREAD

**Issue by miyconst** [Starcounter/starcounter-debug-aid#55]
### Steps to reproduce

- Open a Starcounter website.
- Open the Starcounter Debug Aid popup.
- Make something on the page to cause a patch being sent/received.
- Go to the Patches tab in the SDA.
- Double click on any patch's content, which has some data inside.
- The JSON tree view opens.

### Screenshot

![image](https://user-images.githubusercontent.com/6435556/33241901-98e57c54-d2cc-11e7-8e0d-f54ffd805bda.png)

**Comment by alshakero** [comment]
This should be done in https://github.com/Starcounter/starcounter-debug-aid/commit/97bf60acbccd1c3b56da72729dbd01c2f648de28

Can you do me the favour of checking again before I upload a new version to the store? I'd truly appreciate it.

You can download this [zip](https://github.com/Starcounter/starcounter-debug-aid/blob/extension/build/web-extension.zip).

**Comment by miyconst** [comment]
Works the same for me.

**Comment by alshakero** [comment]
@miyconst can you check in the overlay? (not the pop-up)

**Comment by miyconst** [comment]
Works ok there.

**Comment by alshakero** [comment]
Fixed for sure in https://github.com/Starcounter/starcounter-debug-aid/commit/6d067038e1e774dcefeaa590b12dee84a64d1283.

A check wouldn't hurt though.

**Comment by alshakero** [comment]
Fixed and released 0.0.3. Update should reach you soon in FF and Chrome.
