### ISSUE TITLE
Do not inherit styles from the page

### ISSUE THREAD

**Issue by warpech** [Starcounter/starcounter-debug-aid#56]
The overlay inherits styles from the page stylesheet, which can look bad:

![image](https://user-images.githubusercontent.com/566463/33324460-faffab74-d44f-11e7-8919-73ece3abf4ed.png)

Isolate the CSS in the overlay by using an `<iframe>` or [`all: initial`](https://developer.mozilla.org/en-US/docs/Web/CSS/all).

**Comment by alshakero** [comment]
I was playing around with this yesterday. I'll see what I can do. `iframe` idea doesn't work because I don't think iframes can draw anything outside themselves.

**Comment by alshakero** [comment]
Wow, I tried yesterday `all: unset` and was bad. But `all: initial` works perfect!

**Comment by alshakero** [comment]
Closing as done in https://github.com/Starcounter/starcounter-debug-aid/commit/2c31d072b03e5e9300ba56086d5731694e1f71a0.
