### ISSUE TITLE
[browser extension] warning for non-Starcounter pages

### ISSUE THREAD

**Issue by tomalec** [Starcounter/starcounter-debug-aid#57]
I think the extension should not pollute all pages' console.
### Steps to reproduce
1. Install browser extension,
2. Open non-Starcounter page,
3. Open dev tools

### Expected result
Console should be clean (unless the page itself logs something)

### Actual result
There is always a warning
```
Neither palindrom-client nor puppet-client elements were found!
```

### Browsers affected

- [x] Chrome
- [x] Firefox

### Screenshot

//cc @alshakero

**Comment by alshakero** [comment]
Good point.

**Comment by alshakero** [comment]
Done in https://github.com/Starcounter/starcounter-debug-aid/commit/65d801c7efc4c854f7d00ac0a57185ad6c33e378.
