### ISSUE TITLE
Change `extension` branch to become `master`

### ISSUE THREAD

**Issue by warpech** [Starcounter/starcounter-debug-aid#59]

**Comment by alshakero** [comment]
- Moved old code to [Old-code](https://github.com/Starcounter/starcounter-debug-aid/tree/Old-code ) branch.
- Renamed `extension` to `master`.
- Updated the bookmarklet to use `master` in the [blog post](https://starcounter.io/starcounter-devtools-extension/).

Closing as done.

**Comment by warpech** [comment]
I have renamed the `Old-code` branch to `before-extension`
