### ISSUE TITLE
Popup window is not always on top

### ISSUE THREAD

**Issue by miyconst** [Starcounter/starcounter-debug-aid#62]
I have a `<div style="z-index: 1050;"></div>` on a page, and SDA pops up under it, which is wrong.

**Comment by alshakero** [comment]
Fixed in https://github.com/Starcounter/starcounter-debug-aid/commit/4645e2dcff54705650a07be95df4bc41982cd63a

SDA didn't have any `z-index`. I gave it the [maximum value](https://stackoverflow.com/questions/491052/minimum-and-maximum-value-of-z-index) to ensure it won't be undertaken 😄
